name: Actualizar Calidad del Aire Monterrey

on:
  schedule:
    - cron: '0 */3 * * *'
  workflow_dispatch:

# Otorga permisos explicitos de escritura al workflow
permissions: write-all

jobs:
  build-and-commit:
    runs-on: ubuntu-latest

    steps:
    - name: Clonar Repositorio
      uses: actions/checkout@v4
      with:
        fetch-depth: 0 # Evita errores 128 al hacer commit/push

    - name: Configurar Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Instalar Dependencias
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Ejecutar Extracción
      run: python main.py

    - name: Guardar Cambios en GitHub
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'
        git add data/calidad_aire.csv
        git commit -m "Automated update: Registros de calidad del aire Monterrey" || echo "No hay cambios para guardar"
        git push origin HEAD:${{ github.ref_name }}